name: NPM Publish

on:
  push:
    branches: [main]
  pull_request:
    branches: '*'

jobs:
  quality:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [16]
        os: [ubuntu-latest]

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install package with i
        run: npm install
      - name: Install package
        run: npm ci
    # - run: npm test

  publish:
    needs: [quality]
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
